# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install sudo
      run: sudo apt-get update  
    - name: Display python version installed
      run: echo "Successfully installed package ${{ matrix.python-version}}"
    - name: Install dependencies      
      run: |
        python3 -m pip install --upgrade pip
        pip install pandas
        pip install requests
        pip install openpyxl
        pip install xlrd        
    
    - name: SHA version      
      run:  echo "Successfully commited at ${GITHUB_SHA}"
    - name: Executing python Scripts
      run: |
            chmod +x ./src/TestPython.py
            python3 ./src/TestPython.py >./destination/AutomateQueries.sql
            cat ./destination/AutomateQueries.sql
    - name: check git status 
      run: |
            git config --global user.email "vijayafive@gmail.com"
            git config --global user.name "vijaya-vj"
            git status
            git add ./destination/AutomateQueries.sql
            git commit -m "checkin the change for automated script"
            git push origin main
    - name: SHA version      
      run:  echo "Successfully writing and commiting sql scripts under SHA ${GITHUB_SHA}"
    - name: Status of script execution
      run: echo "Successfully executed python script"
      
          
           
        